# Generated by Django 5.0.6 on 2024-07-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_customuser_managers_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default='2024/07/1', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
