# Generated by Django 5.0.6 on 2024-07-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_booking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfdetails',
            name='price',
            field=models.FloatField(max_length=50),
        ),
    ]
