# Generated by Django 5.0.6 on 2024-07-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_booking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarybookingdata',
            name='booking_id',
            field=models.CharField(default='2024/07-1', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
