# Generated by Django 5.0.6 on 2024-07-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_turfdetails_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_uuid',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
