# Generated by Django 5.0.6 on 2024-07-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_payment_transaction_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default='2022-03-09'),
            preserve_default=False,
        ),
    ]
