# Generated by Django 5.0.6 on 2024-07-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_payment_booking_payment_booking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='booking_id',
            new_name='booking',
        ),
    ]
