# Generated by Django 5.0.6 on 2024-06-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('images', models.JSONField()),
            ],
        ),
    ]
