# Generated by Django 5.0.6 on 2024-06-24 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_turfdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='turfs/')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turf_images', to='base.turfdetails')),
            ],
        ),
    ]
