# Generated by Django 5.0.6 on 2024-06-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_turfimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turfdetails',
            name='images',
        ),
    ]
